notifications:
  email: false

git:
  depth: 3

services:
  - postgresql

language: php
sudo: false

php:
  - 7.4
  - 7.3
  - 7.2

env:
  - DB=sqlite
  - DB=postgres

matrix:
  fast_finish: true

before_script:
  - composer install --no-interaction
  - npm install -g jshint

script:
  - jshint assets/js/{core,components}
  - ./vendor/bin/phpunit -c tests/units.$DB.xml
  - ./vendor/bin/phpunit tests/configtest
